import { ClaudeModel } from '../claude-agent/claude-agent.constants';

/** The model every digest is generated by. Not a setting: the measurements below are its. */
export const MEETING_DIGEST_MODEL = ClaudeModel.SONNET;

/**
 * The bounds of an answer. The schema states them, so the model is told; the guard enforces
 * them, because a schema the provider checks is still the provider's word.
 *
 * Generous rather than tight — a digest that fits them is a page, not a transcript — and
 * there so that no answer, however it came about, can put an unbounded string in a row.
 */
export const MAX_DIGEST_SUMMARY_LENGTH = 4_000;
/**
 * Of action items, and separately of decisions. A meeting that states more gets the most
 * important ones and a summary that says the list is not complete — the instructions ask for
 * both, and `test:live`'s dense measurement holds the model to them past the bound.
 */
export const MAX_DIGEST_ITEMS = 50;
export const MAX_DIGEST_ITEM_LENGTH = 500;
/** A spoken name. As long as a display name may be: a longer one could match nobody. */
export const MAX_DIGEST_OWNER_LENGTH = 80;

/**
 * The most transcript text one generation may carry, counted in characters across all of a
 * meeting's transcripts. Past it nothing is sent and the digest fails as too long: the
 * transcripts go to Claude whole or not at all.
 *
 * Set from the model's documented limits and the measurements in
 * `src/config/meeting-digest.defaults.ts`:
 *
 *     1,000,000 tokens   the context window of `claude-sonnet-5-5`
 *     − 128,000          the most it may answer with, thinking included
 *     −   2,900          the instructions, the schema, and the SDK's framing (measured)
 *     =   869,000 tokens of transcript
 *     ×       2.4        characters a token for Russian, the densest script measured
 *     = 2,060,000 characters of Russian prose
 *
 * and set a sixth below that, because a transcript is not all prose: numbers, names, and
 * the other languages in Cyrillic run denser than the text the 2.4 was measured on.
 *
 * About thirty hours of speech. English is 2.9 characters a token, so the cap stops an
 * English meeting at some 586,000 tokens with room to spare; the price of one number for
 * every language. At the cap a generation costs about $1.50 in English and $1.80 in Russian.
 *
 * **Characters, because tokens cannot be counted without asking Anthropic** — and a script
 * denser than Russian can pass this cap and still be more than the model will read. That is
 * what `ClaudeAgentFailure.PROMPT_TOO_LONG` is for: it ends in the same failure as this cap.
 * A prompt past the context window was refused by Claude Code itself, unsent and unbilled.
 *
 * Both limits are the SDK's own report of the model too (`contextWindow`, `maxOutputTokens`
 * in a result's `modelUsage`), which is where to look when the model changes.
 */
export const MAX_DIGEST_TRANSCRIPT_CHARACTERS = 1_700_000;
