import { Module } from '@nestjs/common';
import { CqrsModule } from '@nestjs/cqrs';

import { AuthModule } from '../auth/auth.module';
import { ClaudeAgentModule } from '../claude-agent/claude-agent.module';
import { RequestDigestWhenTranscribedHandler } from './events/request-digest-when-transcribed.handler';
import { MeetingDigestsController } from './meeting-digests.controller';
import { MEETING_DIGEST_WORKER, MeetingDigestWorker } from './processing/meeting-digest-worker';
import { MeetingDigestClaimRepository } from './services/meeting-digest-claim.repository';
import { MeetingDigestGenerator } from './services/meeting-digest-generator';
import { MeetingDigestRepository } from './services/meeting-digest.repository';
import { MeetingDigestsService } from './services/meeting-digests.service';
import { PENDING_DIGEST_REQUESTS, PendingDigestRequests } from './services/pending-digest-requests';

/**
 * The digest of a meeting — summary, action items, decisions — written by Claude from the
 * transcripts of its recordings: asked for when a recording is transcribed, generated by a
 * worker of its own, stored, and served to whoever can see the meeting.
 *
 * It owns its four tables and imports `ClaudeAgentModule`, and **reaches every other module
 * over the buses only**: whether a meeting is visible is `FindVisibleMeetingQuery`, which
 * recordings are transcribed and what was said in them are two queries `meeting-files`
 * answers, and its trigger is that module's `MeetingFileChangedEvent`. It imports neither
 * `MeetingsModule` nor `MeetingFilesModule`, and reads neither's table.
 */
@Module({
  // `AuthModule` is for the guard on the one route.
  imports: [CqrsModule, AuthModule, ClaudeAgentModule],
  controllers: [MeetingDigestsController],
  providers: [
    MeetingDigestGenerator,
    MeetingDigestRepository,
    MeetingDigestClaimRepository,
    MeetingDigestsService,
    // `@EventsHandler` registers nothing on its own, as a command handler does not: left out
    // of this array, a transcribed recording asks for nothing and nothing says why.
    RequestDigestWhenTranscribedHandler,
    PendingDigestRequests,
    { provide: PENDING_DIGEST_REQUESTS, useExisting: PendingDigestRequests },
    MeetingDigestWorker,
    // Also under a string token, as the two file workers are: the e2e suite drains each of
    // the three by hand, which is how a spec sees a recording transcribed and its digest
    // still queued.
    { provide: MEETING_DIGEST_WORKER, useExisting: MeetingDigestWorker },
  ],
})
export class MeetingDigestsModule {}
