import { Module } from '@nestjs/common';
import { CqrsModule } from '@nestjs/cqrs';

import { AuthModule } from '../auth/auth.module';
import { ClaudeAgentModule } from '../claude-agent/claude-agent.module';
import { MeetingToolsModule } from '../meeting-tools/meeting-tools.module';
import { RetryMeetingDigestHandler } from './commands/handlers/retry-meeting-digest.handler';
import { ReviseMeetingDigestHandler } from './commands/handlers/revise-meeting-digest.handler';
import { RequestDigestWhenTranscribedHandler } from './events/request-digest-when-transcribed.handler';
import { WithdrawDigestWhenDeletedHandler } from './events/withdraw-digest-when-deleted.handler';
import { MeetingDigestsController } from './meeting-digests.controller';
import {
  MEETING_DIGEST_CATCH_UP,
  MeetingDigestCatchUp,
} from './processing/meeting-digest-catch-up';
import { MEETING_DIGEST_WORKER, MeetingDigestWorker } from './processing/meeting-digest-worker';
import { MeetingDigestAnnouncer } from './services/meeting-digest-announcer';
import { MeetingDigestClaimRepository } from './services/meeting-digest-claim.repository';
import { MeetingDigestDeleteFollower } from './services/meeting-digest-delete-follower';
import { MeetingDigestGenerator } from './services/meeting-digest-generator';
import { MeetingDigestRepository } from './services/meeting-digest.repository';
import { MeetingDigestsService } from './services/meeting-digests.service';
import { PENDING_DIGEST_REQUESTS, PendingDigestRequests } from './services/pending-digest-requests';

/**
 * The digest of a meeting — summary, action items, decisions — written by Claude from the
 * transcripts of its recordings: asked for when a recording is transcribed — or at boot, for
 * what no recording will ask for again, or by its host or a recording's uploader, to retry
 * one that failed — generated by a worker of its own, stored, and served to whoever can see
 * the meeting.
 *
 * It owns its four tables and imports `ClaudeAgentModule`, and **reaches every other module
 * over the buses only**: whether a meeting is visible is `FindVisibleMeetingQuery`, which
 * recordings are transcribed — one meeting's, or every meeting's — and what was said in
 * them are three queries `meeting-files` answers, who is in a meeting and what they are
 * called are one query each of `meetings` and `user`, and its trigger is `meeting-files`'
 * `MeetingFileChangedEvent`. It imports none of `MeetingsModule`, `MeetingFilesModule`, and
 * `UserModule`, and reads none of their tables.
 *
 * What it says back is one event, `MeetingDigestChangedEvent`, after every committed write.
 * The files stream forwards it to the meeting's open pages; this module knows no stream.
 */
@Module({
  // `AuthModule` is for the guard on the two routes, and `MeetingToolsModule` for the tools
  // a generation's run is handed. That module reaches this one over the command bus and
  // imports nothing of it, so the two are not a cycle.
  imports: [CqrsModule, AuthModule, ClaudeAgentModule, MeetingToolsModule],
  controllers: [MeetingDigestsController],
  providers: [
    MeetingDigestGenerator,
    MeetingDigestRepository,
    MeetingDigestClaimRepository,
    MeetingDigestsService,
    MeetingDigestAnnouncer,
    MeetingDigestDeleteFollower,
    RetryMeetingDigestHandler,
    ReviseMeetingDigestHandler,
    // `@EventsHandler` registers nothing on its own, as a command handler does not: left out
    // of this array, a transcribed recording asks for nothing, a deleted one is followed by
    // nothing, and nothing says why.
    RequestDigestWhenTranscribedHandler,
    WithdrawDigestWhenDeletedHandler,
    PendingDigestRequests,
    { provide: PENDING_DIGEST_REQUESTS, useExisting: PendingDigestRequests },
    MeetingDigestWorker,
    // Also under a string token, as the two file workers are: the e2e suite drains each of
    // the three by hand, which is how a spec sees a recording transcribed and its digest
    // still queued.
    { provide: MEETING_DIGEST_WORKER, useExisting: MeetingDigestWorker },
    // What asks, at boot, for the digests no recording will ask for again. Under a string
    // token too, for the reason the worker is: a spec runs it by hand.
    MeetingDigestCatchUp,
    { provide: MEETING_DIGEST_CATCH_UP, useExisting: MeetingDigestCatchUp },
  ],
})
export class MeetingDigestsModule {}
