import fs from 'node:fs';
import { open, mkdir, rename, rm, stat, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';

/**
 * The one shape a key may take: `<meetingId>/<fileId>`, optionally with the thumbnail suffix.
 * Anything else throws before touching `fs`. This is the whole path-traversal defence — keys
 * are generated by the module, never derived from a user's filename — and it lives here so
 * every filesystem call is behind it.
 */
const KEY_PATTERN = /^[0-9a-f-]{36}\/[0-9a-f-]{36}(\.thumb\.webp)?$/;

const TEMP_DIR = 'tmp';

/**
 * Meeting file storage over one directory on the local filesystem.
 *
 * The rest of the module never touches `fs`: put, open as a stream, stat, remove, and the two
 * paths the pipeline needs are the whole interface, so a different backend later is one class.
 * The root is created and probed for writability at boot (`onModuleInit`), which is the PRD's
 * "checked then, not at the first upload".
 */
@Injectable()
export class MeetingFileStorage implements OnModuleInit {
  private readonly logger = new Logger(MeetingFileStorage.name);
  private readonly root: string;

  constructor(config: ConfigService) {
    // Relative to the working directory, which for `pnpm dev` and the Dockerfile is `apps/api`.
    this.root = path.resolve(process.cwd(), config.getOrThrow<string>('MEETING_FILES_DIR'));
  }

  async onModuleInit(): Promise<void> {
    const probe = path.join(this.tempDir(), `.probe-${String(process.pid)}`);

    try {
      await mkdir(this.tempDir(), { recursive: true });
      await writeFile(probe, '');
      await unlink(probe);
    } catch (error) {
      throw new Error(
        `Meeting file storage at ${this.root} is not writable: ${errorMessage(error)}`,
        { cause: error },
      );
    }

    this.logger.log(`Meeting file storage at ${this.root}`);
  }

  /** Where multipart uploads land before they are validated and moved into place. */
  tempDir(): string {
    return path.join(this.root, TEMP_DIR);
  }

  /** The absolute path of a key, for the one consumer (`sharp`) that wants a path, not a stream. */
  pathOf(key: string): string {
    return path.join(this.root, assertKey(key));
  }

  /**
   * Moves a file into place under `key`: `fsync` the source so the bytes are on disk before the
   * record that points at them exists, create the key's directory, then `rename`, which is
   * atomic within one filesystem — the temp directory is under the same root for that reason.
   */
  async put(key: string, sourcePath: string): Promise<void> {
    const destination = this.pathOf(key);

    const handle = await open(sourcePath, 'r+');
    try {
      await handle.sync();
    } finally {
      await handle.close();
    }

    await mkdir(path.dirname(destination), { recursive: true });
    await rename(sourcePath, destination);
  }

  openRead(key: string): fs.ReadStream {
    return fs.createReadStream(this.pathOf(key));
  }

  async stat(key: string): Promise<{ size: number }> {
    const { size } = await stat(this.pathOf(key));

    return { size };
  }

  /** Idempotent: a missing object is a removed object. */
  async remove(key: string): Promise<void> {
    await rm(this.pathOf(key), { force: true });
  }
}

function assertKey(key: string): string {
  if (!KEY_PATTERN.test(key)) {
    throw new Error(`Invalid storage key: ${JSON.stringify(key)}`);
  }

  return key;
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
