import fs from 'node:fs';
import { open, mkdir, rename, rm, stat, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';

import { errorMessage } from '../../../common/error-message';

/** A uuid as the module generates them. Never a segment a client chose. */
const ID = String.raw`[0-9a-f-]{36}`;

/**
 * The two shapes a key may take: `<meetingId>/<fileId>` for a stored object, optionally with
 * the thumbnail suffix, and `uploads/<uploadId>/<index>` for one chunk of an upload in
 * progress. Anything else throws before touching `fs`. This is the whole path-traversal
 * defence — keys are generated by the module, never derived from a user's filename — and it
 * lives here so every filesystem call is behind it.
 *
 * The index is the canonical decimal form: no sign, no leading zeros, so one chunk has
 * exactly one key and a resend cannot land beside the chunk it was meant to replace.
 */
const KEY_PATTERN = new RegExp(
  String.raw`^(${ID}\/${ID}(\.thumb\.webp|\.transcript\.txt)?|uploads\/${ID}\/(0|[1-9]\d{0,8}))$`,
);

/** The id segment of an upload's chunk directory, for `removeTree`. */
const ID_PATTERN = new RegExp(String.raw`^${ID}$`);

const TEMP_DIR = 'tmp';
const UPLOADS_DIR = 'uploads';

/**
 * Meeting file storage over one directory on the local filesystem.
 *
 * The rest of the module never touches `fs`: put, open as a stream, stat, remove, and the two
 * paths the pipeline needs are the whole interface, so a different backend later is one class.
 * The root is created and probed for writability at boot (`onModuleInit`), which is the PRD's
 * "checked then, not at the first upload".
 */
@Injectable()
export class MeetingFileStorage implements OnModuleInit {
  private readonly logger = new Logger(MeetingFileStorage.name);
  private readonly root: string;

  constructor(config: ConfigService) {
    // Relative to the working directory, which for `pnpm dev` and the Dockerfile is `apps/api`.
    this.root = path.resolve(process.cwd(), config.getOrThrow<string>('MEETING_FILES_DIR'));
  }

  async onModuleInit(): Promise<void> {
    const probe = path.join(this.tempDir(), `.probe-${String(process.pid)}`);

    try {
      await mkdir(this.tempDir(), { recursive: true });
      await writeFile(probe, '');
      await unlink(probe);
    } catch (error) {
      throw new Error(
        `Meeting file storage at ${this.root} is not writable: ${errorMessage(error)}`,
        { cause: error },
      );
    }

    this.logger.log(`Meeting file storage at ${this.root}`);
  }

  /** Where multipart uploads land before they are validated and moved into place. */
  tempDir(): string {
    return path.join(this.root, TEMP_DIR);
  }

  /** The absolute path of a key, for the one consumer (`sharp`) that wants a path, not a stream. */
  pathOf(key: string): string {
    return path.join(this.root, assertKey(key));
  }

  /**
   * Moves a file into place under `key`: `fsync` the source so the bytes are on disk before the
   * record that points at them exists, create the key's directory, then `rename`, which is
   * atomic within one filesystem — the temp directory is under the same root for that reason.
   */
  async put(key: string, sourcePath: string): Promise<void> {
    await this.move(this.pathOf(key), sourcePath);
  }

  /**
   * `put` for one chunk of an upload session, with the containing directory `fsync`ed too.
   *
   * That extra sync is the difference, and it is the point: the response to a chunk tells the
   * client it never has to send those bytes again. A `rename` is not durable until the
   * directory entry is, so a power loss right after a 204 would otherwise lose a chunk the
   * client has been told to forget — and a resumed upload would assemble a file with a hole
   * in it. For a single-request upload there is no such promise to keep: the row is written in
   * the same request, and a crash before either lands simply means the upload did not happen.
   */
  async putChunk(key: string, sourcePath: string): Promise<void> {
    const destination = this.pathOf(key);

    await this.move(destination, sourcePath);
    await syncDirectory(path.dirname(destination));
  }

  /** Every chunk of one upload session, in one call. Idempotent, like `remove`. */
  async removeTree(uploadId: string): Promise<void> {
    if (!ID_PATTERN.test(uploadId)) {
      throw new Error(`Invalid upload id: ${JSON.stringify(uploadId)}`);
    }

    await rm(path.join(this.root, UPLOADS_DIR, uploadId), { recursive: true, force: true });
  }

  /**
   * Text beside an object — the transcription step's output, written as UTF-8. Here rather
   * than an `fs.writeFile` at the call site, so every filesystem call stays behind the key
   * check: a step writes by key or not at all.
   */
  async writeText(key: string, contents: string): Promise<void> {
    const destination = this.pathOf(key);

    await mkdir(path.dirname(destination), { recursive: true });
    await writeFile(destination, contents, 'utf8');
  }

  openRead(key: string): fs.ReadStream {
    return fs.createReadStream(this.pathOf(key));
  }

  async stat(key: string): Promise<{ size: number }> {
    const { size } = await stat(this.pathOf(key));

    return { size };
  }

  /** Idempotent: a missing object is a removed object. */
  async remove(key: string): Promise<void> {
    await rm(this.pathOf(key), { force: true });
  }

  private async move(destination: string, sourcePath: string): Promise<void> {
    const handle = await open(sourcePath, 'r+');
    try {
      await handle.sync();
    } finally {
      await handle.close();
    }

    await mkdir(path.dirname(destination), { recursive: true });
    await rename(sourcePath, destination);
  }
}

/**
 * `fsync` on a directory, which is how a `rename` is made durable. Not every platform allows
 * opening a directory for sync — macOS and Linux do, and on one that does not the chunk's own
 * bytes are already synced, so the call is skipped rather than failing the upload.
 */
async function syncDirectory(directory: string): Promise<void> {
  const handle = await open(directory, 'r').catch(() => null);

  if (handle === null) {
    return;
  }

  // EINVAL on a filesystem that does not support it; the chunk's own bytes are synced already.
  await handle.sync().catch(() => undefined);
  await handle.close();
}

function assertKey(key: string): string {
  if (!KEY_PATTERN.test(key)) {
    throw new Error(`Invalid storage key: ${JSON.stringify(key)}`);
  }

  return key;
}
